galaxy_info:
  author: DevOps Department
  description: k8s server
  role_name: k8s
  namespace: k8s
  license: Limited License

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - k8s

dependencies: []
