---
# The admin.conf is meant for cluster bootstrapping and emergency access, not day-to-day operations.
- name: K8s - Set KUBECONFIG for root user
  lineinfile:
    path: /root/.bashrc
    line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
    state: present

- name: K8s - Check if cluster is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: cluster_initialized

# This command initializes a Kubernetes control plane node.
- name: K8s - Initialize Kubernetes cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --service-cidr=10.96.0.0/12
  register: kubeadm_init_output
  when: not cluster_initialized.stat.exists

- name: Check if Flannel is already installed
  shell: kubectl get daemonset kube-flannel-ds -n kube-flannel
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: flannel_check
  failed_when: false
  changed_when: false

- name: Install Flannel CNI
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: flannel_check.rc != 0

- name: Wait for Flannel pods to be ready
  shell: kubectl wait --for=condition=Ready pod -l app=flannel -n kube-flannel --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: flannel_check.rc != 0

- name: Wait for nodes to be ready
  shell: kubectl wait --for=condition=Ready node --all --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: flannel_check.rc != 0
