---
- name: Get join command from master
  shell: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ groups['master_servers'][0] }}"
  run_once: true

- name: Join worker nodes to cluster
  shell: "{{ join_command.stdout }}"
  when: inventory_hostname in groups['worker_servers']
